
export const stock = [

    { id: 1, precio: 500, stock: 5, nombre: "Jabon floral - Jazmin", img: "../img/productos/product (1).jpeg", categoria: "jabones", descrip:"Alivia eficazmente las irritaciones. Actúa como cicatrizante. Suaviza las estrías. Otorga mayor elasticidad a la piel. Ayuda a reducir la apariencia de imperfecciones de la piel. Promueve un cutis radiante." },
    { id: 2, precio: 500, stock: 5, nombre: "Jabon floral - Rosas y Calendula", img: "../img/productos/product (2).jpeg", categoria: "jabones",descrip:"La caléndula tiene gran poder cicatrizante, y antiséptico. Regenera la piel y produce colágeno. La rosa mosqueta es regenerador celular, suaviza las manchas de la piel, atenúa arrugas, estimula la circulación sanguínea." },
    { id: 3, precio: 500, stock: 5, nombre: "Jabon floral- Lavanda y Manzanilla", img: "../img/productos/product (3).jpeg", categoria: "jabones",descrip:"Con aceite esencial de manzanilla, tiene acción calmante, es cicatrizante, y antiséptica, ayuda a la prevención de eczemas e infecciones." },
    { id: 4, precio: 500, stock: 5, nombre: "Jabon humectante - Coco y Karite", img: "../img/productos/product (4).jpeg", categoria: "jabones",descrip:"Aceite de coco contiene vitamina E, excelente antiarrugas, ayuda a recuperar la flexibilidad de la piel seca. Karité, es regeneradora y cicatrizante, alivia la irritación de la dermis." },
    { id: 5, precio: 500, stock: 5, nombre: "Jabon humectante -  Aloe vera", img: "../img/productos/product (5).jpeg", categoria: "jabones",descrip:"Sus propiedades antiinflamatorias y analgésicas permiten aliviar el dolor y la inflamación. Es un calmante para la epidermis. Combate la sequedad de la piel" },
    { id: 6, precio: 500, stock: 5, nombre: "Jabon humectante- Miel y Avena", img: "../img/productos/product (6).jpeg", categoria: "velas",descrip:"LA MIEL ES ANTIOXIDANTE, ANTISÉPTICO, CURATIVO, HIDRATANTE, NUTRITIVO, CALMANTE. PERFECTO PARA LA PIEL SECA Y SENSIBLE.LA AVENA TIENE EMOLIENTES MUY EFECTIVAS, FORTALECE LA PIEL, Y RESTAURA LA BARRERA CUTÁNEA. IDEAL PARA EL ACNÉ" },
    { id: 7, precio: 500, stock: 5, nombre: "Jabon exfoliante - Naranja con esponja vegetal", img: "../img/productos/product (5).jpeg", categoria: "jabones",descrip:"Ayuda a nuestro cuerpo a producir colágeno y elastina, manteniendo la elasticidad de la piel, gracias a sus aportes de Vitamina C, Hidratante, revitalizante, suavizante, antioxidante y nutritiva." },
    { id: 8, precio: 500, stock: 5, nombre: "Jabon Exfoliante - Cafe con aceite de almendras", img: "../img/productos/product (5).jpeg", categoria: "jabones",descrip:"Previene la aparicio de estrias, tiene efecto antinflamatorio, elimina ojeras, suaviza arrugas e hidrata la piel" },
    { id: 9, precio: 500, stock: 5, nombre: "Jabon exfoliante - Canela", img: "../img/productos/product (5).jpeg", categoria: "jabones",descrip:"El aceite de almendras previene la aparición de estrías, suaviza arrugas, y elimina ojeras. La canela previene el acné, exfolia, hidrata, es antibacteriana, antiinflamatoria, y cicatrizante." },
    { id: 10, precio: 500, stock: 5, nombre: "Jabon exfoliante - Cafe y Miel", img: "../img/productos/product (5).jpeg", categoria: "jabones",descrip:"Hidrata y exfolia la zona que tiene vellos encarnados para que puedan ser liberados." },
    { id: 11, precio: 500, stock: 5, nombre: "Jabon exfoliante - Masajeador", img: "../img/productos/product (5).jpeg", categoria: "jabones",descrip:"Jabon exfoliante con centella asiatica" },
    { id: 12, precio: 1200, stock: 5, nombre: "Shampoo Solido cabellos grasos/anti caspa", img: "../img/productos/product (5).jpeg", categoria: "pelo",descrip:"Rinde aprox entre 60 y 80 lavados. Elaborados con aceites organicos, no daña ni irrita la piel, ideales para viajes. Contiene Manteca de Karité, Polvo de Jengibre, aceite esencial de Eucalipto, y Romero" },  
    { id: 13, precio: 1200, stock: 5, nombre: "Shampoo Solido cabellos normales a secos", img: "../img/productos/product (5).jpeg", categoria: "pelo",descrip:"Rinde aprox entre 60 y 80 lavados. Elaborados con aceites organicos, no daña ni irrita la piel, ideales para viajes. Contiene Manteca de Karité, aceite esencial de Rosa Mosqueta, Jazmín y Rosas" },
    { id: 14, precio: 1200, stock: 5, nombre: "Acondicionador Solido Fortalecedor", img: "../img/productos/product (5).jpeg", categoria: "pelo",descrip:"Rinde aprox entre 60 y 80 lavados. Elaborados con aceites organicos, no daña ni irrita la piel, ideales para viajes. Contiene  Aceite de Ricino, aceite de coco, manteca de Karité, Cera de Abejas, aceite esencial de Romero y Eucalipto" },
    { id: 15, precio: 1200, stock: 5, nombre: "Acondicionador Solido Humectante", img: "../img/productos/product (5).jpeg", categoria: "pelo",descrip:"Rinde aprox entre 60 y 80 lavados. Elaborados con aceites organicos, no daña ni irrita la piel, ideales para viajes. Contiene Aceite de jojoba, aceite de coco, manteca de Karité, Cera de Abejas." },
    { id: 16, precio: 1200, stock: 5, nombre: "Acondicionador Solido Cabellos Grasos", img: "../img/productos/product (5).jpeg", categoria: "pelo",descrip:"Rinde aprox entre 60 y 80 lavados. Elaborados con aceites organicos, no daña ni irrita la piel, ideales para viajes. Contiene Aceite de coco, manteca de Karité, Cera de Abejas, aceite de semillas de uva." },
    { id: 17, precio: 1200, stock: 5, nombre: "Acondicionador Solido Nutritivo", img: "../img/productos/product (5).jpeg", categoria: "pelo",descrip:"Rinde aprox entre 60 y 80 lavados. Elaborados con aceites organicos, no daña ni irrita la piel, ideales para viajes. Contiene Aceite de argán, aceite de coco, manteca de Karité, Cera de Abejas, aceite esencial de Rosa Mosqueta y Jazmín" },

]


